[project]
name = 'Decentralized-Specialized-Rare-Plant-Conservation'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.species-registry]
path = 'contracts/species-registry.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
